### ISSUE TITLE
Replicating Data Set - 137 Materials Missing

### ISSUE THREAD

**Issue by CompRhys** [CJBartel/TestStabilityML#1]
I am attempting to replicate the Ef data set investigated to look at other properties using the following code: 
```
m = MPRester("<id>")
df_hd = pd.read_json("ef.json").T
target_properties = ["task_id", "pretty_formula",
                                "band_gap","formation_energy_per_atom",]
data = m.query(criteria={'task_ids':{'$in':df_hd["ID"].tolist()}}, 
                                        properties=target_properties)
df_mp = pd.DataFrame(data)
```

for the 85014 materials in `ef.json`  we only get 84877 materials back from the query. Of these 9343 appear to have had their materials ids changed making it hard to try track down the missing 137 materials. 

This probably isn't statistically significant but maybe worth flagging up as it means strict comparisons to the bench-marking results presented here aren't possible if further data from materials project is required i.e. when looking for multi-task models.

**Comment by CJBartel** [comment]
Thanks for posting this. Good point - I hadn't considered reproducibility as it pertains to the simultaneous learning of multiple properties. 

I'll do some poking around MP to see if there's a way to track these missing materials down and will include a note in the docs regarding the fluidity of MP.
