### ISSUE TITLE
Were tests performed training CGCNN directly on decomposition energy instead of implicitly via convex hull calculations?

### ISSUE THREAD

**Issue by sgbaird** [CJBartel/TestStabilityML#2]
@CJBartel I noticed that Fig. 3, which is trained on formation energies followed by convex hull predictions of decomposition energy ($\Delta H_d$), has higher MAEs than Fig S3, which is trained directly on the decomposition energy. The trends are also somewhat different qualitatively. I was looking around the main and supplementary articles and had trouble finding a comparison where CGCNN is trained directly on decomposition energy (i.e. to compare with Fig 7b). Was this test performed? If so, what were the results?

**Comment by CJBartel** [comment]
We did not ever perform that test, though I would be curious what the results look like. Trying to recall our thought process for not performing it, I think it boiled down to 1) the very poor performance of compositional models trained on Hd for the Li-Mn-TM-O test and 2) feeling the paper was already a bit overwhelming in terms of number of analyses performed.
