### ISSUE TITLE
Is the CGCNN output data available?

### ISSUE THREAD

**Issue by sgbaird** [CJBartel/TestStabilityML#3]
E.g. https://github.com/CJBartel/TestStabilityML/tree/master/mlstabilitytest/ml_data/Ed/allMP

**Comment by CJBartel** [comment]
Please see my comment to the other related issue. Because we did not train CGCNN on Ed, there are no `.../Ed/*/CGCNN/` folders with output data. For the CGCNN models trained on Ef, you can find output data in `.../Ef/*/CGCNN/*.json`

**Comment by sgbaird** [comment]
Ah, I feel silly. For some reason, I wasn't looking at the Ef folder. Thank you!
